require 'logger'
require 'redis'
require 'ontologies_linked_data'
require 'ncbo_annotator'
require_relative 'ncbo_cron/ontology_submission_parser'
require_relative 'ncbo_cron/ontology_pull'
require_relative 'ncbo_cron/scheduler'